### ISSUE TITLE
Please add English GUI

### ISSUE THREAD

**Issue by probonopd** [sigoden/alphat#1]
Right now this is what you see when you launch the application on a non-Asian system.

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/df80f72a1461fd84d93719fce3d7709ff436e080/database/AlphaT/screenshot.png)

**Comment by sigoden** [comment]
[v0.5.0](https://github.com/sigoden/alphat/releases/tag/v0.5.0) enable i18n

**Comment by sigoden** [comment]
update your application to latest version

**Comment by probonopd** [comment]
Thank you.
